### ISSUE TITLE
Deprecation warnings are raised

### ISSUE THREAD

**Issue by Julian-O** [dessant/support-requests#11]
Using this action generates warnings:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dessant/support-requests@v2. [...]

[Example](https://github.com/kivy/pyjnius/actions/runs/6642129491)

**Comment by dessant** [comment]
Fixed in version 4.

```yaml
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v4
```
